name: senslerdeutsches-woerterbuch
services:

  proxy:
    build: 
      context: .
      dockerfile: docker/proxy/Dockerfile
    ports:
      - "${PROXY_PORT}:80"
    volumes:
      - ./docker/proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/proxy/logs/nginx:/var/log/nginx
    networks:
      - sw-network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - discovery.type=single-node # Required to disable SSL while keeping security enabled
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data  # Persist API keys and indices locally
    deploy:
      resources:
        limits:
          memory: 1GB
    networks:
      - sw-network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  setup:
    build:
      context: .
      dockerfile: docker/setup/Dockerfile
    environment:
      - PROXY_URL=http://elasticsearch
      - PROXY_PORT=9200
      - PROXY_SUFFIX= # Needs to be empty to avoid "None"
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_INDEX=${ELASTIC_INDEX}
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - sw-network

  e2e:
    build:
      context: .
      dockerfile: docker/e2e/Dockerfile
    environment:
      - FRONTEND_URL=${PROXY_URL}
    volumes:
      - ./e2e/playwright-report:/app/playwright-report
      - ./e2e/test-results:/app/test-results
    depends_on:
      setup:
        condition: service_completed_successfully
    networks:
      - sw-network

networks:
  sw-network:
    driver: bridge

volumes:
  elasticsearch-data: