name: Build and Push to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: az acr login --name ${{ env.ACR_NAME }}

    - name: Build and push proxy
      run: |
        docker build . -f ./docker/proxy/Dockerfile \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/proxy:${{ github.sha }} \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/proxy:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/proxy:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/proxy:latest

    - name: Build and push backend
      run: |
        docker build . -f ./docker/backend/Dockerfile \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:${{ github.sha }} \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest
