# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./senslerdeutsches-woerterbuch

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: |
          ./senslerdeutsches-woerterbuch/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run Angular Unit Tests
      run: npx ng test --no-watch --no-progress --browsers=ChromeHeadless
