name: E2e tests with Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          echo "ELASTIC_PASSWORD=changeme" > .env
          echo "ELASTIC_INDEX=dictionary" >> .env
          echo "PROXY_PORT=4202" >> .env
          echo "PROXY_URL=http://frontend" >> .env
          echo "FRONTEND_PORT=4201" >> .env

      - name: Run setup and prepare environment
        run: |
          docker compose up -d elasticsearch proxy 
          docker compose up setup --exit-code-from setup
          echo "✅ Setup completed successfully"

      - name: Run E2E tests
        run: docker compose up e2e --exit-code-from e2e
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1

      - name: Save Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./e2e/playwright-report/
          retention-days: 30

      - name: Save test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: ./e2e/test-results/
          retention-days: 7