name: E2e tests with Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          # Start with defaults
          cp .env.defaults .env

          # Add a newline to ensure clean append
          echo "" >> .env
          
          # Add sensitive values
          echo "ELASTIC_ADMIN_PASSWORD=${{ secrets.ELASTIC_ADMIN_PASSWORD || 'changeme' }}" >> .env

      - name: Debug .env file
        run: |
          echo "CONTENTS OF .env FILE:"
          cat .env
          
          echo "ENVIRONMENT VARIABLES IN DOCKER COMPOSE:"
          docker compose config | grep -A10 setup:

      - name: Run setup and prepare environment
        run: |
          docker compose up -d elasticsearch proxy 
          docker compose up setup --exit-code-from setup
          echo "✅ Setup completed successfully"

      - name: Debug container networking
        if: always()
        run: |
          echo "==== CONTAINER STATUS ===="
          docker compose ps
          
          echo "==== ELASTICSEARCH STATUS ===="
          docker compose exec -T elasticsearch curl -s -u elastic:${{ secrets.ELASTIC_ADMIN_PASSWORD}} http://localhost:9200/_cat/indices
          docker compose exec -T elasticsearch curl -s -u elastic:${{ secrets.ELASTIC_ADMIN_PASSWORD}} http://localhost:9200/_security/user
          
          echo "==== PROXY TEST ===="
          docker compose exec -T proxy curl -s -u dictionary_reader:thisisgonnabepublic -H "Content-Type: application/json" http://elasticsearch:9200/dictionary/_search -d '{"query":{"match_all":{}}}'
          
          echo "==== TEST FROM E2E CONTAINER ===="
          docker compose run --rm e2e curl -s -v http://proxy/
          docker compose run --rm e2e curl -s -v -u dictionary_reader:thisisgonnabepublic -H "Content-Type: application/json" http://proxy/elastic/_search -d '{"query":{"match":{"term":"wundere"}}}'

      - name: Run E2E tests
        run: docker compose up e2e --exit-code-from e2e
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1

      - name: Save Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./e2e/playwright-report/
          retention-days: 30

      - name: Save test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: ./e2e/test-results/
          retention-days: 7