name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    # Build the Angular application to use for testing
    - name: Install Angular dependencies
      working-directory: ./senslerdeutsches-woerterbuch
      run: npm ci
    
    - name: Build Angular app
      working-directory: ./senslerdeutsches-woerterbuch
      run: npm run build -- --configuration=production

    - name: Install Playwright Browsers
      working-directory: ./e2e
      run: npx playwright install --with-deps

    # Install and serve the Angular application
    - name: Install serve package
      working-directory: ./e2e
      run: npm install serve

    - name: Run Playwright tests
      working-directory: ./e2e
      run: npx playwright test

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30