# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: |
          ./senslerdeutsches-woerterbuch/package-lock.json

    - name: Install
      working-directory: ./senslerdeutsches-woerterbuch
      run: npm ci

    - name: Build
      run: npm run build --if-present
      working-directory: ./senslerdeutsches-woerterbuch

    - uses: browser-actions/setup-chrome@v1

    - name: Test
      run: npx ng test --no-watch --no-progress --browsers=ChromeHeadless
      working-directory: ./senslerdeutsches-woerterbuch
